
version: 2.1
jobs:
  build:
    docker:
      - image: ubuntu:18.04
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Install Docker client
          command: |
            set -x
            VER="19.03.5-ce"
            sudo curl -L -o /tmp/docker-$VER.tgz https://download.docker.com/linux/static/stable/x86_64/docker-$VER.tgz
            sudo tar -xz -C /tmp -f /tmp/docker-$VER.tgz
            sudo mv /tmp/docker/* /usr/bin
            echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin

      - deploy: 
          name: Build & Push
          command: |
            docker build -t $DOCKER_USERNAME/docker-salesforce-ant:latest .
            if [ "${CIRCLE_BRANCH}" == "master" ]; then
              docker push $DOCKER_USERNAME/docker-salesforce-ant:latest
            fi
